export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_ERROR = 'CHANGE_PASS_ERROR';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const CHANGE_AVATAR_ERROR = 'CHANGE_AVATAR_ERROR';

//Stats HTTP requests
export const GET_STATS = 'GET_STATS';
export const GET_STATS_FAIL = 'GET_STATS_FAIL';

//Appointment HTTP requests
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const UPDATE_APPOINTMENT_FAIL = 'UPDATE_APPOINTMENT_FAIL';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CREATE_APPOINTMENT_FAIL = 'CREATE_APPOINTMENT_FAIL';

//Comment HTTP requests
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_VIDEO_COMMENTS = 'GET_VIDEO_COMMENTS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';
export const GET_VIDEO_COMMENTS_FAIL = 'GET_VIDEO_COMMENTS_FAIL';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

//Video HTTP requests
export const CLEAN_VIDEO = 'CLEAN_VIDEO';
export const GET_VIDEO = 'GET_VIDEO';
export const POST_VIDEO = 'POST_VIDEO';
export const POST_VIDEO_FAIL = 'POST_VIDEO_FAIL';
export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEO_FAIL = 'GET_VIDEO_FAIL';
export const GET_VIDEOS_FAIL = 'GET_VIDEOS_FAIL';
export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const UPDATE_VIDEO_FAIL = 'UPDATE_VIDEO_FAIL';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL';


//AdminInfo HTTP requests
export const GET_INFO = 'GET_INFO';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';
export const UPDATE_INFO = 'UPDATE_INFO';
export const UPDATE_INFO_FAIL = 'UPDATE_INFO_FAIL';


//Giveaway HTTP requests
export const GET_SUBMISSION = 'GET_SUBMISSION';
export const GET_SUBMISSION_FAIL = 'GET_SUBMISSION_FAIL';
export const DELETE_SUBMISSION = 'DELETE_SUBMISSION';
export const DELETE_SUBMISSION_FAIL = 'DELETE_SUBMISSION_FAIL';
export const GET_SUBMISSIONS = 'GET_SUBMISSIONS';
export const GET_SUBMISSIONS_FAIL = 'GET_SUBMISSIONS_FAIL';
export const POST_SUBMISSION = 'POST_SUBMISSION';
export const POST_SUBMISSION_FAIL = 'POST_SUBMISSION_FAIL';

